name: test

namespace:
  number: 1

tuningSets:
- name: Uniform1qps
  qpsLoad:
    qps: 1

steps:
- name: Start measurements
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployment
      Params:
        apiVersion: apps/v1
        kind: Deployment
        labelSelector: group = test-deployment
        operationTimeout: 120s
    - Identifier: WaitForRunningDeployment2
      Params:
        apiVersion: apps/v1
        kind: Deployment
        labelSelector: group = test-deployment-2
        operationTimeout: 120s
    Params:
      action: start  
# - name: Start measurements
#   measurements:
#   - Identifier: WaitForControlledPodsRunning
#     Method: WaitForControlledPodsRunning
#     Params:
#       action: start
#       apiVersion: apps/v1
#       kind: Deployment
#       labelSelector: group = test-deployment
#       operationTimeout: 120s

  # - Identifier: APIAvailability
  #   Method: APIAvailability
  #   Params:
  #     action: start
  #     pollFrequency: "5s"
  #     hostPollTimeoutSeconds: 5
  #     threshold: 99.50
- name: Create deployments
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: Uniform1qps
    objectBundle:
    - basename: test-deployment
      objectTemplatePath: "deployment.yaml"
      templateFillMap:
        Replicas: 3
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: Uniform1qps
    objectBundle:
    - basename: test-deployment-2
      objectTemplatePath: "deployment2.yaml"
      templateFillMap:
        Replicas: 3
- name: Wait for pods to be running
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployment
    - Identifier: WaitForRunningDeployment2
    Params:
      action: gather

# - name: Sleep
#   measurements:
#   - Identifier: WaitAfterExec
#     Method: Sleep
#     Params:
#       duration: 120s
      
# - name: Measure pod startup latency
#   measurements:
#   - Identifier: PodStartupLatency
#     Method: PodStartupLatency
#     Params:
#       action: gather
#   - Identifier: APIAvailability
#     Method: APIAvailability
#     Params:
#       action: gather
#       pollFrequency: "5s"
#       hostPollTimeoutSeconds: 5
#       threshold: 99.50