apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: {{ .Name }}
spec:
  distinguisherMethod:
    type: ByNamespace
  matchingPrecedence: 4000
  priorityLevelConfiguration:
    name: {{ .PriorityLevelName }}
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - "configmaps"
      verbs:
      - "list"
    subjects:
      - kind: ServiceAccount
        serviceAccount:
          name: default
          namespace: {{ .PodsNamespace }}